In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv(r'C:\Users\windows10\Desktop\Hands_on_Machine_Learniing\code_basics\ML\2_linear_reg_multivariate\homeprices.csv')

In [3]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

#### Data Preprocessing: Fill NA values with median value of a column

In [8]:
df.bedrooms.median()

4.0

In [11]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())

In [12]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [14]:
# Lets split the data into X and y
X = df.drop('price', axis = 1)
y = df.price

In [15]:
reg = LinearRegression()
reg.fit(X, y) # Fit the Lineear Regression model to the data

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [17]:
reg.intercept_

221323.00186540408

In [18]:
# Lets predict one value where area = 3000, bedrooms = 3, age = 40 years
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [19]:
# Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old
reg.predict([[2500, 4, 5]])

array([578876.03748933])

In [24]:
df1 = pd.read_csv(r'C:\Users\windows10\Desktop\Hands_on_Machine_Learniing\code_basics\ML\2_linear_reg_multivariate\Exercise\hiring.csv')

In [26]:
df1.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [31]:
type(df1.experience)

pandas.core.series.Series

In [32]:
df1.experience = df1.experience.fillna('zero')

In [36]:
df1.isna().sum()

experience                    0
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [40]:
# Lets Convert the experience column tonumerical values
from word2number import w2n
df1.experience = df1.experience.apply(w2n.word_to_num)

In [41]:
df1.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000

In [43]:
import math
median_test_score = math.floor(df1['test_score(out of 10)'].mean())
median_test_score

7

In [44]:
df1['test_score(out of 10)'] = df1['test_score(out of 10)'].fillna(median_test_score)

In [45]:
df1.isna().sum()

experience                    0
test_score(out of 10)         0
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [47]:
lin_reg = LinearRegression()
lin_reg.fit(df1[['experience','test_score(out of 10)','interview_score(out of 10)']], df1['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [48]:
lin_reg.predict([[2,9,6]])

array([53713.86677124])

In [49]:
lin_reg.predict([[12,10,10]])

array([93747.79628651])

In [50]:
lin_reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [51]:
lin_reg.intercept_

14992.65144669314