### Ridge Regression

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge

In [2]:
ridge_reg = Ridge(alpha = 1, solver="cholesky")

In [3]:
m = 100
X = 6 * np.random.rand(m, 1) - 3
y = 0.5 * X**2 + X + 2 + np.random.randn(m, 1)

In [4]:
ridge_reg.fit(X, y)

Ridge(alpha=1, copy_X=True, fit_intercept=True, max_iter=None, normalize=False,
      random_state=None, solver='cholesky', tol=0.001)

In [5]:
ridge_reg.predict([[1.5]])

array([[5.08977964]])

### Using Stochastic Gradient Descent

In [6]:
from sklearn.linear_model import SGDRegressor
sgd_reg = SGDRegressor(penalty= "l2")

In [7]:
sgd_reg.fit(X, y.ravel())

SGDRegressor(alpha=0.0001, average=False, early_stopping=False, epsilon=0.1,
             eta0=0.01, fit_intercept=True, l1_ratio=0.15,
             learning_rate='invscaling', loss='squared_loss', max_iter=1000,
             n_iter_no_change=5, penalty='l2', power_t=0.25, random_state=None,
             shuffle=True, tol=0.001, validation_fraction=0.1, verbose=0,
             warm_start=False)

In [8]:
sgd_reg.predict([[1.5]])

array([5.05511851])

### Lasso Regression

In [10]:
from sklearn.linear_model import Lasso

In [11]:
lasso_reg = Lasso(alpha = 0.1)
lasso_reg.fit(X, y)

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [12]:
lasso_reg.predict([[1.5]])

array([5.04632946])

### Using Stochastic Gradient Descent

In [13]:
from sklearn.linear_model import SGDRegressor
sgd_reg1 = SGDRegressor(penalty= "l1")

In [15]:
sgd_reg1.fit(X, y.ravel())

SGDRegressor(alpha=0.0001, average=False, early_stopping=False, epsilon=0.1,
             eta0=0.01, fit_intercept=True, l1_ratio=0.15,
             learning_rate='invscaling', loss='squared_loss', max_iter=1000,
             n_iter_no_change=5, penalty='l1', power_t=0.25, random_state=None,
             shuffle=True, tol=0.001, validation_fraction=0.1, verbose=0,
             warm_start=False)

In [16]:
sgd_reg1.predict([[1.5]])

array([5.07081231])

### Elastic Net

In [17]:
from sklearn.linear_model import ElasticNet
elastic_net = ElasticNet(alpha=0.1, l1_ratio=0.5)
elastic_net.fit(X, y)
elastic_net.predict([[1.5]])

array([5.04806219])